FROM alpine:latest

RUN apk add openjdk11-jdk
RUN apk add nodejs
RUN apk add npm
RUN apk add curl
COPY . /usr/src/yavin
COPY yavin-run.sh /usr/local/bin/
WORKDIR /usr/src/yavin/
RUN ./gradlew build -x test -Penvironment=production
WORKDIR /
RUN cp /usr/src/yavin/ws/build/libs/yavin-app*.jar /usr/local/lib/
RUN rm -rf /usr/src/yavin
